In [1]:
import pathlib

import polars
import rich

from data_index.iceberg_config import SqliteCatalogConfig, IcebergTableConfig

In [18]:
# --- Local SQLite Iceberg config ---
local_warehouse = pathlib.Path("/Users/thommodin/dev/data-index/.load/orchestrate-local")
local_warehouse.mkdir(parents=True, exist_ok=True)

data_index_catalog_config = SqliteCatalogConfig(
    name="data-index",
    uri=f"sqlite:///{local_warehouse / 'catalog.db'}",
    warehouse=str(local_warehouse),
)

table = IcebergTableConfig(
    catalog_config=data_index_catalog_config,
    namespace="data_index",
    table_name="structured_metadata_v6",
).load()

In [19]:
# Read into memory as polars.DataFrame
df = table.scan().to_polars()
display(df)

shape: (17_000, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ bucket    ┆ key       ┆ version_i ┆ hash      ┆ … ┆ variable_ ┆ coordinat ┆ dimension ┆ standard │
│ ---       ┆ ---       ┆ d         ┆ ---       ┆   ┆ schema    ┆ e_schema  ┆ _sizes    ┆ _names   │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ list[stru ┆ list[stru ┆ list[stru ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆ ct[2]]    ┆ ct[2]]    ┆ ct[2]]    ┆ uct[2]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ 2aa4474b8 ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /csio/290 ┆           ┆ 83f16e3f4 ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 2691/2902 ┆           ┆ 0c0352d73 ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ 691…      ┆           ┆ 183…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ 0fd5b0507 ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /csio/290 ┆           ┆ f292c5d31 ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 2692/2902 ┆           ┆ c86ff8142 ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ 692…      ┆           ┆ e2b…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ 17d77a470 ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /csio/290 ┆           ┆ a1a5366e8 ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 2693/2902 ┆           ┆ 90b744706 ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ 693…      ┆           ┆ 3e4…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ a71557126 ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /csio/290 ┆           ┆ 44ed44833 ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 2694/2902 ┆           ┆ f11a511b5 ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ 694…      ┆           ┆ 385…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ 6842be781 ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /csio/290 ┆           ┆ cc53e1515 ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 2695/2902 ┆           ┆ b4a8cd32d ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ 695…      ┆           ┆ 56c…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ 4f71ccffb ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /aoml/158 ┆           ┆ 82a5b7731 ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 51/15851_ ┆           ┆ ba0122928 ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ pro…      ┆           ┆ e85…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ 96908046f ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /aoml/158 ┆           ┆ ebb36af02 ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 52/15852_ ┆           ┆ 1de4620db ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ pro…      ┆           ┆ 4cc…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ a3fdb7f50 ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /aoml/158 ┆           ┆ 72e8ae88e ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 53/15853_ ┆           ┆ 77430b26b ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ pro…      ┆           ┆ 2ef…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ d2f74b473 ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /aoml/158 ┆           ┆ a009b93fe ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 54/15854_ ┆           ┆ e98df592e ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ pro…      ┆           ┆ ae0…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
│ /Volumes/ ┆ IMOS/Argo ┆ __LOCAL__ ┆ 639c1f976 ┆ … ┆ [{"CONFIG ┆ []        ┆ [{"N_CALI ┆ [{"JULD" │
│ 4tb-0/imo ┆ /aoml/158 ┆           ┆ ccb9ecd2f ┆   ┆ _MISSION_ ┆           ┆ B",1},    ┆ ,"time"} │
│ s-data    ┆ 55/15855_ ┆           ┆ 03f6bd9ff ┆   ┆ NUMBER"," ┆           ┆ {"N_HISTO ┆ , {"LATI │
│           ┆ pro…      ┆           ┆ 777…      ┆   ┆ flo…      ┆           ┆ RY",0…    ┆ TUDE",…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
display(df["coordinate_schema"].value_counts(sort=True))
display(df["variable_schema"].value_counts(sort=True))
display(df["schema_version"].value_counts(sort=True))

shape: (1, 2)
┌───────────────────┬───────┐
│ coordinate_schema ┆ count │
│ ---               ┆ ---   │
│ list[struct[2]]   ┆ u32   │
╞═══════════════════╪═══════╡
│ []                ┆ 17000 │
└───────────────────┴───────┘

shape: (2, 2)
┌─────────────────────────────────┬───────┐
│ variable_schema                 ┆ count │
│ ---                             ┆ ---   │
│ list[struct[2]]                 ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ [{"CONFIG_MISSION_NUMBER","flo… ┆ 16930 │
│ [{"CONFIG_MISSION_NUMBER","flo… ┆ 70    │
└─────────────────────────────────┴───────┘

shape: (1, 2)
┌────────────────┬───────┐
│ schema_version ┆ count │
│ ---            ┆ ---   │
│ i64            ┆ u32   │
╞════════════════╪═══════╡
│ 6              ┆ 17000 │
└────────────────┴───────┘

In [ ]:
df["variable_schema"]
df.with_columns(
    # Extract keys list
    polars.col("variable_schema").list.eval(polars.element().struct.field(name="key")).alias("schema_keys"),
    
    # Extract values list
    polars.col("variable_schema").list.eval(polars.element().struct.field(name="value")).alias("schema_values")
).select("schema_keys")

shape: (17_000, 1)
┌─────────────────────────────────┐
│ schema_keys                     │
│ ---                             │
│ list[str]                       │
╞═════════════════════════════════╡
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ …                               │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
│ ["CONFIG_MISSION_NUMBER", "CYC… │
└─────────────────────────────────┘

In [ ]:

df["variable_schema"].value_counts(sort=True)["variable_schema"].filter(
    polars.element()
).to_list()[0]

[{'key': 'CONFIG_MISSION_NUMBER', 'value': 'float64'},
 {'key': 'CYCLE_NUMBER', 'value': 'float64'},
 {'key': 'DATA_CENTRE', 'value': 'object'},
 {'key': 'DATA_MODE', 'value': 'object'},
 {'key': 'DATA_STATE_INDICATOR', 'value': 'object'},
 {'key': 'DATA_TYPE', 'value': 'object'},
 {'key': 'DATE_CREATION', 'value': 'object'},
 {'key': 'DATE_UPDATE', 'value': 'object'},
 {'key': 'DC_REFERENCE', 'value': 'object'},
 {'key': 'DIRECTION', 'value': 'object'},
 {'key': 'FIRMWARE_VERSION', 'value': 'object'},
 {'key': 'FLOAT_SERIAL_NO', 'value': 'object'},
 {'key': 'FORMAT_VERSION', 'value': 'object'},
 {'key': 'HANDBOOK_VERSION', 'value': 'object'},
 {'key': 'HISTORY_ACTION', 'value': 'object'},
 {'key': 'HISTORY_DATE', 'value': 'object'},
 {'key': 'HISTORY_INSTITUTION', 'value': 'object'},
 {'key': 'HISTORY_PARAMETER', 'value': 'object'},
 {'key': 'HISTORY_PREVIOUS_VALUE', 'value': 'float32'},
 {'key': 'HISTORY_QCTEST', 'value': 'object'},
 {'key': 'HISTORY_REFERENCE', 'value': 'object'},
 {'key': 'HISTORY_SOFTWARE', 'value': 'object'},
 {'key': 'HISTORY_SOFTWARE_RELEASE', 'value': 'object'},
 {'key': 'HISTORY_START_PRES', 'value': 'float32'},
 {'key': 'HISTORY_STEP', 'value': 'object'},
 {'key': 'HISTORY_STOP_PRES', 'value': 'float32'},
 {'key': 'JULD', 'value': 'datetime64[ns]'},
 {'key': 'JULD_LOCATION', 'value': 'datetime64[ns]'},
 {'key': 'JULD_QC', 'value': 'object'},
 {'key': 'LATITUDE', 'value': 'float64'},
 {'key': 'LONGITUDE', 'value': 'float64'},
 {'key': 'PARAMETER', 'value': 'object'},
 {'key': 'PI_NAME', 'value': 'object'},
 {'key': 'PLATFORM_NUMBER', 'value': 'object'},
 {'key': 'PLATFORM_TYPE', 'value': 'object'},
 {'key': 'POSITIONING_SYSTEM', 'value': 'object'},
 {'key': 'POSITION_QC', 'value': 'object'},
 {'key': 'PRES', 'value': 'float32'},
 {'key': 'PRES_ADJUSTED', 'value': 'float32'},
 {'key': 'PRES_ADJUSTED_ERROR', 'value': 'float32'},
 {'key': 'PRES_ADJUSTED_QC', 'value': 'object'},
 {'key': 'PRES_QC', 'value': 'object'},
 {'key': 'PROFILE_PRES_QC', 'value': 'object'},
 {'key': 'PROFILE_PSAL_QC', 'value': 'object'},
 {'key': 'PROFILE_TEMP_QC', 'value': 'object'},
 {'key': 'PROJECT_NAME', 'value': 'object'},
 {'key': 'PSAL', 'value': 'float32'},
 {'key': 'PSAL_ADJUSTED', 'value': 'float32'},
 {'key': 'PSAL_ADJUSTED_ERROR', 'value': 'float32'},
 {'key': 'PSAL_ADJUSTED_QC', 'value': 'object'},
 {'key': 'PSAL_QC', 'value': 'object'},
 {'key': 'REFERENCE_DATE_TIME', 'value': 'object'},
 {'key': 'SCIENTIFIC_CALIB_COEFFICIENT', 'value': 'object'},
 {'key': 'SCIENTIFIC_CALIB_COMMENT', 'value': 'object'},
 {'key': 'SCIENTIFIC_CALIB_DATE', 'value': 'object'},
 {'key': 'SCIENTIFIC_CALIB_EQUATION', 'value': 'object'},
 {'key': 'STATION_PARAMETERS', 'value': 'object'},
 {'key': 'TEMP', 'value': 'float32'},
 {'key': 'TEMP_ADJUSTED', 'value': 'float32'},
 {'key': 'TEMP_ADJUSTED_ERROR', 'value': 'float32'},
 {'key': 'TEMP_ADJUSTED_QC', 'value': 'object'},
 {'key': 'TEMP_QC', 'value': 'object'},
 {'key': 'VERTICAL_SAMPLING_SCHEME', 'value': 'object'},
 {'key': 'WMO_INST_TYPE', 'value': 'object'}]