In [1]:
import os

from data_index.iceberg_config import S3TablesCatalogConfig, IcebergTableConfig

os.environ["AWS_PROFILE"] = "edge-admin"

In [3]:
# --- Sink config ---
data_index_catalog_config = S3TablesCatalogConfig(
    region="ap-southeast-2",
    arn="arn:aws:s3tables:ap-southeast-2:704910415367:bucket/data-index",
)

structured_metadata_table_config = IcebergTableConfig(
    catalog_config=data_index_catalog_config,
    namespace="data_index",
    table_name=f"structured_metadata_v1",
)

unstructured_metadata_table_config = IcebergTableConfig(
    catalog_config=data_index_catalog_config,
    namespace="data_index",
    table_name="unstructured_metadata",
)

In [4]:
structured_metadata = structured_metadata_table_config.load()

In [5]:
structured_metadata.metadata

TableMetadataV2(location='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3', table_uuid=UUID('e62303dc-16dd-4807-a284-a8a0eb776251'), last_updated_ms=1781591690696, last_column_id=26, schemas=[Schema(NestedField(field_id=1, name='s3_uri', field_type=StringType(), required=True), NestedField(field_id=2, name='lat_min', field_type=DoubleType(), required=False), NestedField(field_id=3, name='lat_max', field_type=DoubleType(), required=False), NestedField(field_id=4, name='lon_min', field_type=DoubleType(), required=False), NestedField(field_id=5, name='lon_max', field_type=DoubleType(), required=False), NestedField(field_id=6, name='time_min', field_type=StringType(), required=False), NestedField(field_id=7, name='time_max', field_type=StringType(), required=False), NestedField(field_id=8, name='crs', field_type=StringType(), required=False), NestedField(field_id=9, name='keywords', field_type=StringType(), required=False), NestedField(field_id=10, name='conventions', field_type=StringType(), required=False), NestedField(field_id=11, name='file_version', field_type=StringType(), required=False), NestedField(field_id=12, name='metadata_uuid', field_type=StringType(), required=False), NestedField(field_id=13, name='platform_code', field_type=StringType(), required=False), NestedField(field_id=14, name='site_code', field_type=StringType(), required=False), NestedField(field_id=15, name='deployment_code', field_type=StringType(), required=False), NestedField(field_id=16, name='instrument', field_type=StringType(), required=False), NestedField(field_id=17, name='feature_type', field_type=StringType(), required=False), NestedField(field_id=18, name='instrument_serial_number', field_type=StringType(), required=False), NestedField(field_id=19, name='dimensions', field_type=ListType(type='list', element_id=24, element_type=StringType(), element_required=True), required=False), NestedField(field_id=20, name='variables', field_type=ListType(type='list', element_id=25, element_type=StringType(), element_required=True), required=False), NestedField(field_id=21, name='standard_names', field_type=ListType(type='list', element_id=26, element_type=StringType(), element_required=True), required=False), NestedField(field_id=22, name='file_format', field_type=StringType(), required=False), NestedField(field_id=23, name='collection', field_type=StringType(), required=False), schema_id=0, identifier_field_ids=[])], current_schema_id=0, partition_specs=[PartitionSpec(spec_id=0)], default_spec_id=0, last_partition_id=999, properties={'write.parquet.compression-codec': 'zstd'}, current_snapshot_id=2905712945311298136, snapshots=[Snapshot(snapshot_id=4169534411069669783, parent_snapshot_id=3164303377390394119, sequence_number=25, timestamp_ms=1781503739532, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-4169534411069669783-0-b1aff476-37ea-4f86-8d4a-fdbfd99dbec0.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '8', 'total-position-deletes': '0', 'added-files-size': '13085', 'total-delete-files': '0', 'total-files-size': '1230656', 'total-data-files': '2', 'total-records': '22454'}), schema_id=0), Snapshot(snapshot_id=4959964702471846390, parent_snapshot_id=4169534411069669783, sequence_number=26, timestamp_ms=1781584347528, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-4959964702471846390-0-3b7e0ab7-8383-4602-8a49-090ba5d3fa80.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '34231', 'total-delete-files': '0', 'total-files-size': '1264887', 'total-data-files': '3', 'total-records': '23454'}), schema_id=0), Snapshot(snapshot_id=3901950790875797285, parent_snapshot_id=4959964702471846390, sequence_number=27, timestamp_ms=1781584400565, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-3901950790875797285-0-a0ec9200-e25c-4af5-81bd-512e1107e381.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '33970', 'total-delete-files': '0', 'total-files-size': '1298857', 'total-data-files': '4', 'total-records': '24454'}), schema_id=0), Snapshot(snapshot_id=6940229129832704604, parent_snapshot_id=3901950790875797285, sequence_number=28, timestamp_ms=1781584476068, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-6940229129832704604-0-35b2f5fc-cf3b-4490-9d25-456fadbde395.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '34124', 'total-delete-files': '0', 'total-files-size': '1332981', 'total-data-files': '5', 'total-records': '25454'}), schema_id=0), Snapshot(snapshot_id=3312256873496748194, parent_snapshot_id=6940229129832704604, sequence_number=29, timestamp_ms=1781584544682, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-3312256873496748194-0-d4beefa1-c129-4efe-bdac-fa80ef1fa752.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '34236', 'total-delete-files': '0', 'total-files-size': '1367217', 'total-data-files': '6', 'total-records': '26454'}), schema_id=0), Snapshot(snapshot_id=2327380181284813493, parent_snapshot_id=3312256873496748194, sequence_number=30, timestamp_ms=1781584852614, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-2327380181284813493-0-03a49b11-feef-42ff-b841-dbe0a71bba51.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '34026', 'total-delete-files': '0', 'total-files-size': '1401243', 'total-data-files': '7', 'total-records': '27454'}), schema_id=0), Snapshot(snapshot_id=3626458865749237965, parent_snapshot_id=2327380181284813493, sequence_number=31, timestamp_ms=1781584975603, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-3626458865749237965-0-e72f19a6-3041-4907-98f7-886ae499ef76.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '34073', 'total-delete-files': '0', 'total-files-size': '1435316', 'total-data-files': '8', 'total-records': '28454'}), schema_id=0), Snapshot(snapshot_id=9108353590378156207, parent_snapshot_id=3626458865749237965, sequence_number=32, timestamp_ms=1781584983767, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-9108353590378156207-0-554a6956-331c-47be-bdbe-f5e732476ece.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '33709', 'total-delete-files': '0', 'total-files-size': '1469025', 'total-data-files': '9', 'total-records': '29454'}), schema_id=0), Snapshot(snapshot_id=8301032154733398003, parent_snapshot_id=9108353590378156207, sequence_number=33, timestamp_ms=1781585062274, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-8301032154733398003-0-0fbd8c96-1e32-4f5c-a19c-137d9164bd8f.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '63476', 'total-delete-files': '0', 'total-files-size': '1532501', 'total-data-files': '10', 'total-records': '30454'}), schema_id=0), Snapshot(snapshot_id=5995535462551802440, parent_snapshot_id=8301032154733398003, sequence_number=34, timestamp_ms=1781585254439, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-5995535462551802440-0-782d036f-f954-4ffc-b920-b0000f83acc6.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '33990', 'total-delete-files': '0', 'total-files-size': '1566491', 'total-data-files': '11', 'total-records': '31454'}), schema_id=0), Snapshot(snapshot_id=3674836340231359319, parent_snapshot_id=5995535462551802440, sequence_number=35, timestamp_ms=1781585286249, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-3674836340231359319-0-feb35dd8-4ece-4954-b895-d27c3f2b3c1a.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '64281', 'total-delete-files': '0', 'total-files-size': '1630772', 'total-data-files': '12', 'total-records': '32454'}), schema_id=0), Snapshot(snapshot_id=3390865276345783107, parent_snapshot_id=3674836340231359319, sequence_number=36, timestamp_ms=1781585304544, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-3390865276345783107-0-74d2ef57-6582-47e2-b4f4-215cb976d0eb.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '44047', 'total-delete-files': '0', 'total-files-size': '1674819', 'total-data-files': '13', 'total-records': '33454'}), schema_id=0), Snapshot(snapshot_id=2728394838460266470, parent_snapshot_id=3390865276345783107, sequence_number=37, timestamp_ms=1781585308765, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-2728394838460266470-0-143f0b3d-924a-4d00-9a06-74e51c5abb3e.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '33569', 'total-delete-files': '0', 'total-files-size': '1708388', 'total-data-files': '14', 'total-records': '34454'}), schema_id=0), Snapshot(snapshot_id=6728590762727316372, parent_snapshot_id=2728394838460266470, sequence_number=38, timestamp_ms=1781585368267, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-6728590762727316372-0-c1f58148-82ae-4199-8b0a-6f5ce5056537.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '64323', 'total-delete-files': '0', 'total-files-size': '1772711', 'total-data-files': '15', 'total-records': '35454'}), schema_id=0), Snapshot(snapshot_id=8742721419522232139, parent_snapshot_id=6728590762727316372, sequence_number=39, timestamp_ms=1781585482797, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-8742721419522232139-0-7b80c049-9e79-4849-90c3-70a1a8c12535.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '63637', 'total-delete-files': '0', 'total-files-size': '1836348', 'total-data-files': '16', 'total-records': '36454'}), schema_id=0), Snapshot(snapshot_id=7086781257149552470, parent_snapshot_id=8742721419522232139, sequence_number=40, timestamp_ms=1781585495068, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-7086781257149552470-0-da877d7f-9ced-4b8f-b3aa-be3fce6c63c7.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '73913', 'total-delete-files': '0', 'total-files-size': '1910261', 'total-data-files': '17', 'total-records': '37454'}), schema_id=0), Snapshot(snapshot_id=2026577510411974897, parent_snapshot_id=7086781257149552470, sequence_number=41, timestamp_ms=1781585563367, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-2026577510411974897-0-f53fda52-fd12-49ae-b73b-f31dd9b746f7.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '79537', 'total-delete-files': '0', 'total-files-size': '1989798', 'total-data-files': '18', 'total-records': '38454'}), schema_id=0), Snapshot(snapshot_id=2595311101210980478, parent_snapshot_id=2026577510411974897, sequence_number=42, timestamp_ms=1781585693821, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-2595311101210980478-0-edb1a2f7-f6f0-4ae6-a11b-3e5f686943f4.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '64493', 'total-delete-files': '0', 'total-files-size': '2054291', 'total-data-files': '19', 'total-records': '39454'}), schema_id=0), Snapshot(snapshot_id=1493533407624055310, parent_snapshot_id=2595311101210980478, sequence_number=43, timestamp_ms=1781585705928, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-1493533407624055310-0-07ee9af6-240f-47b8-83b6-35cf4b8f7c99.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '63958', 'total-delete-files': '0', 'total-files-size': '2118249', 'total-data-files': '20', 'total-records': '40454'}), schema_id=0), Snapshot(snapshot_id=1874149493388082173, parent_snapshot_id=1493533407624055310, sequence_number=44, timestamp_ms=1781585796855, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-1874149493388082173-0-28b19d29-0633-4103-89ed-31f078ba3903.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '64123', 'total-delete-files': '0', 'total-files-size': '2182372', 'total-data-files': '21', 'total-records': '41454'}), schema_id=0), Snapshot(snapshot_id=4523668229949289202, parent_snapshot_id=1874149493388082173, sequence_number=45, timestamp_ms=1781585916248, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-4523668229949289202-0-f1f4ba24-e097-4a0f-9138-8c50cba72d77.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '63990', 'total-delete-files': '0', 'total-files-size': '2246362', 'total-data-files': '22', 'total-records': '42454'}), schema_id=0), Snapshot(snapshot_id=2417569279336663200, parent_snapshot_id=4523668229949289202, sequence_number=46, timestamp_ms=1781585925953, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-2417569279336663200-0-9bca8c40-476c-4165-bae4-f560266a65ea.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '98795', 'total-delete-files': '0', 'total-files-size': '2345157', 'total-data-files': '23', 'total-records': '43454'}), schema_id=0), Snapshot(snapshot_id=7374695631872456885, parent_snapshot_id=2417569279336663200, sequence_number=47, timestamp_ms=1781585934495, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-7374695631872456885-0-24ddf2f7-1a52-4ede-b086-a2d6ea4478a9.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '97343', 'total-delete-files': '0', 'total-files-size': '2442500', 'total-data-files': '24', 'total-records': '44454'}), schema_id=0), Snapshot(snapshot_id=8215156066140024998, parent_snapshot_id=7374695631872456885, sequence_number=48, timestamp_ms=1781585981085, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-8215156066140024998-0-b46010b2-3025-43e8-9b73-1e60abd323aa.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '99676', 'total-delete-files': '0', 'total-files-size': '2542176', 'total-data-files': '25', 'total-records': '45454'}), schema_id=0), Snapshot(snapshot_id=3294750323777848857, parent_snapshot_id=8215156066140024998, sequence_number=49, timestamp_ms=1781585987810, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-3294750323777848857-0-0bfc85ab-60fa-4b8e-99de-dbe7221459c6.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '64413', 'total-delete-files': '0', 'total-files-size': '2606589', 'total-data-files': '26', 'total-records': '46454'}), schema_id=0), Snapshot(snapshot_id=5323065912975905365, parent_snapshot_id=3294750323777848857, sequence_number=50, timestamp_ms=1781586467766, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-5323065912975905365-0-aa36396e-2ee3-469d-9b6d-61d5597fbcfc.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '98923', 'total-delete-files': '0', 'total-files-size': '2705512', 'total-data-files': '27', 'total-records': '47454'}), schema_id=0), Snapshot(snapshot_id=1962935861409287000, parent_snapshot_id=5323065912975905365, sequence_number=51, timestamp_ms=1781586707526, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-1962935861409287000-0-9541d635-9edb-4f3f-b795-163e07cb4949.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '97888', 'total-delete-files': '0', 'total-files-size': '2803400', 'total-data-files': '28', 'total-records': '48454'}), schema_id=0), Snapshot(snapshot_id=9012643533400318987, parent_snapshot_id=1962935861409287000, sequence_number=52, timestamp_ms=1781586722122, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-9012643533400318987-0-10754a4f-ba57-46ec-99e3-4d4fdef2b307.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '99256', 'total-delete-files': '0', 'total-files-size': '2902656', 'total-data-files': '29', 'total-records': '49454'}), schema_id=0), Snapshot(snapshot_id=7831011358666189108, parent_snapshot_id=9012643533400318987, sequence_number=53, timestamp_ms=1781587090596, manifest_list='s3://fc019015-d1af-4f1c-jgfii1w38xdo8neewhtryug8pizqgaps2b--table-s3/metadata/snap-7831011358666189108-0-bee380bc-ae86-4cba-9efb-ab478e347b8b.avro', summary=Summary(Operation.APPEND, **{'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '1000', 'total-position-deletes': '0', 'added-files-size': '99396', 'total-delete-files': '0', 'total-files-size': '3002052', 'total-data-files': '30', 'total-records': '50454'}), schema_id=0), 

In [10]:
print(structured_metadata.schema().model_dump_json(indent=2))

{
  "type": "struct",
  "fields": [
    {
      "id": 1,
      "name": "s3_uri",
      "type": "string",
      "required": true
    },
    {
      "id": 2,
      "name": "lat_min",
      "type": "double",
      "required": false
    },
    {
      "id": 3,
      "name": "lat_max",
      "type": "double",
      "required": false
    },
    {
      "id": 4,
      "name": "lon_min",
      "type": "double",
      "required": false
    },
    {
      "id": 5,
      "name": "lon_max",
      "type": "double",
      "required": false
    },
    {
      "id": 6,
      "name": "time_min",
      "type": "string",
      "required": false
    },
    {
      "id": 7,
      "name": "time_max",
      "type": "string",
      "required": false
    },
    {
      "id": 8,
      "name": "crs",
      "type": "string",
      "required": false
    },
    {
      "id": 9,
      "name": "keywords",
      "type": "string",
      "required": false
    },
    {
      "id": 10,
      "name": "conventions",
      "type": "string",
      "required": false
    },
    {
      "id": 11,
      "name": "file_version",
      "type": "string",
      "required": false
    },
    {
      "id": 12,
      "name": "metadata_uuid",
      "type": "string",
      "required": false
    },
    {
      "id": 13,
      "name": "platform_code",
      "type": "string",
      "required": false
    },
    {
      "id": 14,
      "name": "site_code",
      "type": "string",
      "required": false
    },
    {
      "id": 15,
      "name": "deployment_code",
      "type": "string",
      "required": false
    },
    {
      "id": 16,
      "name": "instrument",
      "type": "string",
      "required": false
    },
    {
      "id": 17,
      "name": "feature_type",
      "type": "string",
      "required": false
    },
    {
      "id": 18,
      "name": "instrument_serial_number",
      "type": "string",
      "required": false
    },
    {
      "id": 19,
      "name": "dimensions",
      "type": {
        "type": "list",
        "element-id": 24,
        "element": "string",
        "element-required": true
      },
      "required": false
    },
    {
      "id": 20,
      "name": "variables",
      "type": {
        "type": "list",
        "element-id": 25,
        "element": "string",
        "element-required": true
      },
      "required": false
    },
    {
      "id": 21,
      "name": "standard_names",
      "type": {
        "type": "list",
        "element-id": 26,
        "element": "string",
        "element-required": true
      },
      "required": false
    },
    {
      "id": 22,
      "name": "file_format",
      "type": "string",
      "required": false
    },
    {
      "id": 23,
      "name": "collection",
      "type": "string",
      "required": false
    }
  ],
  "schema-id": 0,
  "identifier-field-ids": []
}

# Full structured_metadata table

In [13]:
con = structured_metadata.scan().to_duckdb(table_name="structured_metadata")

In [20]:
con.execute("""
    SELECT COUNT(*)
    FROM structured_metadata
"""
).fetchone()

(91983,)

In [16]:
con.execute("""
    SELECT *
    FROM structured_metadata
    ORDER BY s3_uri
"""
).fetchdf()

,s3_uri,lat_min,lat_max,lon_min,lon_max,time_min,time_max,crs,keywords,conventions,...,site_code,deployment_code,instrument,feature_type,instrument_serial_number,dimensions,variables,standard_names,file_format,collection
0,s3://imos-data/IMOS/AATAMS/AATAMS_sattag_nrt/Q...,-49.652300,-49.652300,70.795700,70.795700,2009-02-09T17:30:00Z,2009-02-09T17:30:00Z,None,Oceans>Ocean Temperature>Water Temperature;Oce...,"CF-1.6,IMOS-1.3",...,NaN,NaN,NaN,NaN,NaN,"[INSTANCE, PRES]","[PSAL, TEMP, WMO_ID]","[latitude, longitude, sea_water_pressure, sea_...",NETCDF4,None
1,s3://imos-data/IMOS/AATAMS/AATAMS_sattag_nrt/Q...,-50.333900,-50.333900,71.715800,71.715800,2009-02-10T08:00:00Z,2009-02-10T08:00:00Z,None,Oceans>Ocean Temperature>Water Temperature;Oce...,"CF-1.6,IMOS-1.3",...,NaN,NaN,NaN,NaN,NaN,"[INSTANCE, PRES]","[PSAL, TEMP, WMO_ID]","[latitude, longitude, sea_water_pressure, sea_...",NETCDF4,None
2,s3://imos-data/IMOS/AATAMS/AATAMS_sattag_nrt/Q...,-53.999300,-53.999300,76.106800,76.106800,2009-02-14T04:10:00Z,2009-02-14T04:10:00Z,None,Oceans>Ocean Temperature>Water Temperature;Oce...,"CF-1.6,IMOS-1.3",...,NaN,NaN,NaN,NaN,NaN,"[INSTANCE, PRES]","[PSAL, TEMP, WMO_ID]","[latitude, longitude, sea_water_pressure, sea_...",NETCDF4,None
3,s3://imos-data/IMOS/AATAMS/AATAMS_sattag_nrt/Q...,-54.274900,-54.274900,76.380500,76.380500,2009-02-14T10:20:00Z,2009-02-14T10:20:00Z,None,Oceans>Ocean Temperature>Water Temperature;Oce...,"CF-1.6,IMOS-1.3",...,NaN,NaN,NaN,NaN,NaN,"[INSTANCE, PRES]","[PSAL, TEMP, WMO_ID]","[latitude, longitude, sea_water_pressure, sea_...",NETCDF4,None
4,s3://imos-data/IMOS/AATAMS/AATAMS_sattag_nrt/Q...,-54.274900,-54.274900,76.380500,76.380500,2009-02-14T10:20:00Z,2009-02-14T10:20:00Z,None,Oceans>Ocean Temperature>Water Temperature;Oce...,"CF-1.6,IMOS-1.3",...,NaN,NaN,NaN,NaN,NaN,"[INSTANCE, PRES]","[PSAL, TEMP, WMO_ID]","[latitude, longitude, sea_water_pressure, sea_...",NETCDF4,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91978,s3://imos-data/IMOS/eMII/test_files/IMOS/DWM/S...,-46.792048,-46.792048,141.794356,141.794356,2018-03-22T12:00:00Z,2019-02-25T12:00:00Z,None,Oceans->Ocean Chemistry->Biogeochemical Cycles...,"CF-1.6,IMOS-1.4",...,SOTS,SAZ47-20-2018,McLane-PARFLUX-Mark78H-21,timeSeries,"frame controller sn 12419-01, frame sn 12419-0...","[TIME, bnds]","[BSi_mass_flux, BSi_mass_flux_quality_control,...","[depth, latitude, longitude, time]",NETCDF4,None
91979,s3://imos-data/IMOS/eMII/test_files/IMOS/DWM/S...,-47.011100,-47.011100,142.213500,142.213500,2018-02-08T23:00:25Z,2018-03-22T03:00:24Z,None,Oceans; Atmosphere,"CF-1.6,IMOS-1.4",...,SOTS,SOFS-7-2018,MicroStrain 3DM-GX1,timeSeries,5357,"[TIME, frequency, quaternion, sample_time, vec...","[SWH, SWH_quality_control, acceleration, attit...","[depth, latitude, longitude, sea_surface_wave_...",NETCDF4,None
91980,s3://imos-data/IMOS/eMII/test_files/IMOS/DWM/S...,-47.011100,-47.011100,142.213500,142.213500,2018-02-08T23:00:25Z,2018-03-22T03:00:24Z,None,Oceans; Atmosphere,"CF-1.6,IMOS-1.4",...,SOTS,SOFS-7-2018,MicroStrain 3DM-GX1,timeSeries,5357,"[TIME, frequency, quaternion, sample_time, vec...","[SWH, SWH_quality_control, acceleration, attit...","[depth, latitude, longitude, sea_surface_wave_...",NETCDF4,None
91981,s3://imos-data/IMOS/eMII/test_files/IMOS/DWM/S...,-46.893349,-46.893349,142.344635,142.344635,2019-03-18T00:00:00Z,2020-09-14T00:00:00Z,None,NaN,"CF-1.6,IMOS-1.4",...,SOTS,SOFS-8-2019,Microstrain 3DM-GX1,timeSeries,9476,"[FREQ, TIME]","[VAVH, WDS, station_name]","[depth, latitude, longitude, sea_surface_wave_...",NETCDF3_CLASSIC,None
91982,s3://imos-data/IMOS/eMII/test_files/IMOS/DWM/S...,-46.893349,-46.893349,142.344635,142.344635,2019-03-18T00:00:00Z,2020-09-14T00:00:00Z,None,NaN,"CF-1.6,IMOS-1.4",...,SOTS,SOFS-8-2019,Microstrain 3DM-GX1,timeSeries,9476,"[FREQ, TIME]","[VAVH, WDS, station_name]","[depth, latitude, longitude, sea_surface_wave_...",NETCDF3_CLASSIC,None

In [26]:
con.execute("""
    SELECT regexp_extract(s3_uri, 's3://imos-data/([^/]+/[^/]+)', 1) as prefix,
           COUNT(*) as n_files,
           COUNT(DISTINCT site_code) as n_sites,
           COUNT(DISTINCT platform_code) as n_platforms,
           COUNT(DISTINCT deployment_code) as n_deployments,
           COUNT(DISTINCT instrument) as n_instruments
    FROM structured_metadata
    GROUP BY prefix
    ORDER BY prefix
"""
).fetchdf()

,prefix,n_files,n_sites,n_platforms,n_deployments,n_instruments
0,IMOS/AATAMS,17810,0,384,25,0
1,IMOS/ACORN,11884,23,19,0,5
2,IMOS/ACORN_JCU_historical,13128,8,8,0,1
3,IMOS/ANFOG,20,0,11,20,0
4,IMOS/ANMN,12016,226,226,2091,137
5,IMOS/AUV,4420,1,2,0,0
6,IMOS/Argo,2020,0,0,0,0
7,IMOS/COASTAL-WAVE-BUOYS,1274,0,0,0,8
8,IMOS/DWM,8923,18,22,106,103
9,IMOS/FAIMMS,1762,39,39,0,10
10,IMOS/NTP,169,10,5,7,11
11,IMOS/OceanCurrent,14478,0,1,0,0
12,IMOS/SOOP,2014,3,144,0,6
13,IMOS/SRS,2013,2,0,0,7
14,IMOS/eMII,52,15,18,17,15

# Moorings queries

In [34]:
con.execute("""
    CREATE OR REPLACE VIEW anmn_all AS
    SELECT *,
           regexp_extract(s3_uri, 's3://imos-data/IMOS/ANMN/([^/]+)', 1) as subfac,
           regexp_extract(s3_uri, 's3://imos-data/(.*)', 1) as key,
           regexp_extract(file_version, 'Level ([0-4])', 1) as fv
    FROM structured_metadata
    WHERE s3_uri LIKE 's3://imos-data/IMOS/ANMN/%'
"""
)

In [36]:
con.execute("""
    SELECT subfac, COUNT(*) as n_files, COUNT(DISTINCT site_code) as n_sites
    FROM anmn_all
    GROUP BY subfac
    ORDER BY subfac
"""
).fetchdf()

             subfac  n_files  n_sites
0                AM       18        4
1  Deep_Water_Waves        2        0
2               NRS     6185       12
3               NSW     3220       16
4                PA       16        3
5               QLD     1392       28
6                SA      880      158
7                WA      295        9
8        Wave_Buoys        8        0

# Find duplicates

In [12]:
con.execute("""
    SELECT *
    FROM structured_metadata
    WHERE file_version LIKE 'Level 1%'
    ORDER BY s3_uri
"""
).fetchdf()

,s3_uri,time_min,time_max,keywords,file_version,site_code,deployment_code,instrument,feature_type,dimensions,variables,standard_names
0,s3://imos-data/IMOS/ANMN/AM/GBRWIS/CO2/delayed...,2018-02-15T04:00:00Z,2018-09-05T22:00:00Z,Oceans>Ocean Temperature>Sea Surface Temperatu...,Level 1 - Quality Controlled data,GBRWIS,GBRWIS-CO2-1802,NaN,NaN,"[LATITUDE, LONGITUDE, TIME]","[DOX1, DOX1_quality_control, DOXS, DOXS_qualit...","[air_pressure_at_sea_level, air_pressure_at_se..."
1,s3://imos-data/IMOS/ANMN/AM/GBRWIS/CO2/delayed...,2021-03-27T10:00:00Z,2021-09-20T04:00:00Z,Oceans>Ocean Temperature>Sea Surface Temperatu...,Level 1 - Quality Controlled data,GBRWIS,GBRWIS-CO2-2103,NaN,NaN,"[LATITUDE, LONGITUDE, TIME]","[DOX1, DOX1_quality_control, DOXS, DOXS_qualit...","[air_pressure_at_sea_level, air_pressure_at_se..."
2,s3://imos-data/IMOS/ANMN/AM/NRSKAI/CO2/delayed...,2016-08-17T04:00:00Z,2016-11-28T20:00:00Z,Oceans>Ocean Temperature>Sea Surface Temperatu...,Level 1 - Quality Controlled data,NRSKAI,NRSKAI-CO2-1608,NaN,NaN,"[LATITUDE, LONGITUDE, TIME]","[DOX1, DOX1_quality_control, DOXS, DOXS_qualit...","[air_pressure_at_sea_level, air_pressure_at_se..."
3,s3://imos-data/IMOS/ANMN/AM/NRSKAI/CO2/delayed...,2019-11-18T04:00:00Z,2020-11-13T21:00:00Z,Oceans>Ocean Temperature>Sea Surface Temperatu...,Level 1 - Quality Controlled data,NRSKAI,NRSKAI-CO2-1911,NaN,NaN,"[LATITUDE, LONGITUDE, TIME]","[DOX1, DOX1_quality_control, DOXS, DOXS_qualit...","[air_pressure_at_sea_level, air_pressure_at_se..."
4,s3://imos-data/IMOS/ANMN/AM/NRSKAI/CO2/delayed...,2021-11-17T04:00:00Z,2022-05-09T00:00:00Z,Oceans>Ocean Temperature>Sea Surface Temperatu...,Level 1 - Quality Controlled data,NRSKAI,NRSKAI-CO2-2111,NaN,NaN,"[LATITUDE, LONGITUDE, TIME]","[DOX1, DOX1_quality_control, DOXS, DOXS_qualit...","[air_pressure_at_sea_level, air_pressure_at_se..."
...,...,...,...,...,...,...,...,...,...,...,...,...
5845,s3://imos-data/IMOS/ANMN/WA/WATR50/Velocity/IM...,2013-03-19T08:00:00Z,2013-10-04T03:30:00Z,"LongRanger, TIME, HEIGHT_ABOVE_SENSOR, DIST_AL...",Level 1 - Quality Controlled Data,WATR50,WATR50-1303,RDI LongRanger,NaN,"[HEIGHT_ABOVE_SENSOR, TIME]","[ABSI1, ABSI1_quality_control, ABSI2, ABSI2_qu...","[depth, depth status_flag, direction_of_sea_wa..."
5846,s3://imos-data/IMOS/ANMN/WA/WATR50/Velocity/IM...,2017-03-08T00:00:00Z,2017-11-09T01:00:00Z,"LongRanger, TIME, HEIGHT_ABOVE_SENSOR, DIST_AL...",Level 1 - Quality Controlled Data,WATR50,WATR50-1703,RDI LongRanger,NaN,"[HEIGHT_ABOVE_SENSOR, TIME]","[ABSI1, ABSI1_quality_control, ABSI2, ABSI2_qu...","[depth, depth status_flag, direction_of_sea_wa..."
5847,s3://imos-data/IMOS/ANMN/WA/WATR50/Velocity/IM...,2019-09-26T08:00:00Z,2020-03-27T02:30:00Z,"LongRanger, TIME, HEIGHT_ABOVE_SENSOR, DIST_AL...",Level 1 - Quality Controlled Data,WATR50,WATR50-1909,RDI LongRanger,NaN,"[HEIGHT_ABOVE_SENSOR, TIME]","[ABSI1, ABSI1_quality_control, ABSI2, ABSI2_qu...","[depth, depth status_flag, direction_of_sea_wa..."
5848,s3://imos-data/IMOS/ANMN/WA/WATR50/Velocity/IM...,2022-04-07T08:01:31Z,2022-11-03T00:31:31Z,"Signature55, TIME, DIST_ALONG_BEAMS, TIMESERIE...",Level 1 - Quality Controlled Data,WATR50,WATR50-2204,Nortek Signature55,NaN,"[HEIGHT_ABOVE_SENSOR, TIME]","[ABSI1, ABSI1_quality_control, ABSI2, ABSI2_qu...","[depth, depth status_flag, direction_of_sea_wa..."
5849,s3://imos-data/IMOS/ANMN/WA/WATR50/Velocity/IM...,2025-08-18T08:01:00Z,2026-03-20T00:16:00Z,"Signature55, TIME, DIST_ALONG_BEAMS, TIMESERIE...",Level 1 - Quality Controlled Data,WATR50,WATR50-2508,Nortek Signature55,NaN,"[HEIGHT_ABOVE_SENSOR, TIME]","[ABSI1, ABSI1_quality_control, ABSI2, ABSI2_qu...","[depth, depth status_flag, direction_of_sea_wa..."