In [ ]:
import orjson
import genson
import natsort
import thefuzz
import rich
from data_index.iceberg_config import S3TablesCatalogConfig, IcebergTableConfig

In [ ]:
# --- Sinks config ---
data_index_catalog_config = S3TablesCatalogConfig(
    region="ap-southeast-2",
    arn="arn:aws:s3tables:ap-southeast-2:704910415367:bucket/data-index",
)

structured_table = IcebergTableConfig(
    catalog_config=data_index_catalog_config,
    namespace="data_index",
    table_name=f"structured_metadata_v1",
).load()

unstructured_table = IcebergTableConfig(
    catalog_config=data_index_catalog_config,
    namespace="data_index",
    table_name="unstructured_metadata",
).load()

In [11]:
# Read into memory as polars.DataFrame
sdf = structured_table.scan().to_polars()
udf = unstructured_table.scan().to_polars()
display(sdf)
display(udf)

shape: (14_660, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ s3_uri    ┆ lat_min   ┆ lat_max   ┆ lon_min   ┆ … ┆ variables ┆ standard_ ┆ file_form ┆ collecti │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ names     ┆ at        ┆ on       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ list[str] ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s3://imos ┆ -46.66442 ┆ -46.66442 ┆ 142.06278 ┆ … ┆ ["TEMP"]  ┆ ["depth", ┆ NETCDF4   ┆ null     │
│ -data/IMO ┆           ┆           ┆           ┆   ┆           ┆ "latitude ┆           ┆          │
│ S/DWM/SOT ┆           ┆           ┆           ┆   ┆           ┆ ", …      ┆           ┆          │
│ S/2…      ┆           ┆           ┆           ┆   ┆           ┆ "time"…   ┆           ┆          │
│ s3://imos ┆ -46.77725 ┆ -46.77725 ┆ 141.99289 ┆ … ┆ ["TEMP",  ┆ ["depth", ┆ NETCDF4   ┆ null     │
│ -data/IMO ┆           ┆           ┆           ┆   ┆ "TEMP_qua ┆ "latitude ┆           ┆          │
│ S/DWM/SOT ┆           ┆           ┆           ┆   ┆ lity_cont ┆ ", …      ┆           ┆          │
│ S/2…      ┆           ┆           ┆           ┆   ┆ rol…      ┆ "time"…   ┆           ┆          │
│ s3://imos ┆ -46.654   ┆ -46.6517  ┆ 142.106   ┆ … ┆ ["AIRT",  ┆ ["air_pre ┆ NETCDF3_C ┆ null     │
│ -data/IMO ┆           ┆           ┆           ┆   ┆ "AIRT1_5M ┆ ssure",   ┆ LASSIC    ┆          │
│ S/DWM/ASF ┆           ┆           ┆           ┆   ┆ ", …      ┆ "air_temp ┆           ┆          │
│ S/S…      ┆           ┆           ┆           ┆   ┆ "histor…  ┆ arat…     ┆           ┆          │
│ s3://imos ┆ -46.7537  ┆ -46.7298  ┆ 141.92    ┆ … ┆ ["AIRT",  ┆ ["air_pre ┆ NETCDF3_C ┆ null     │
│ -data/IMO ┆           ┆           ┆           ┆   ┆ "AIRT1_5M ┆ ssure",   ┆ LASSIC    ┆          │
│ S/DWM/ASF ┆           ┆           ┆           ┆   ┆ ", …      ┆ "air_temp ┆           ┆          │
│ S/S…      ┆           ┆           ┆           ┆   ┆ "histor…  ┆ arat…     ┆           ┆          │
│ s3://imos ┆ -46.7534  ┆ -46.7441  ┆ 141.961   ┆ … ┆ ["AIRT",  ┆ ["air_pre ┆ NETCDF3_C ┆ null     │
│ -data/IMO ┆           ┆           ┆           ┆   ┆ "AIRT1_5M ┆ ssure",   ┆ LASSIC    ┆          │
│ S/DWM/ASF ┆           ┆           ┆           ┆   ┆ ", …      ┆ "air_temp ┆           ┆          │
│ S/S…      ┆           ┆           ┆           ┆   ┆ "histor…  ┆ arat…     ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s3://imos ┆ -24.19581 ┆ -21.92031 ┆ 150.78170 ┆ … ┆ ["LATITUD ┆ null      ┆ NETCDF3_C ┆ null     │
│ -data/IMO ┆ 2         ┆           ┆ 1         ┆   ┆ E_quality ┆           ┆ LASSIC    ┆          │
│ S/ACORN_J ┆           ┆           ┆           ┆   ┆ _control" ┆           ┆           ┆          │
│ CU_…      ┆           ┆           ┆           ┆   ┆ , "…      ┆           ┆           ┆          │
│ s3://imos ┆ -24.19581 ┆ -21.92031 ┆ 150.78170 ┆ … ┆ ["LATITUD ┆ null      ┆ NETCDF3_C ┆ null     │
│ -data/IMO ┆ 2         ┆           ┆ 1         ┆   ┆ E_quality ┆           ┆ LASSIC    ┆          │
│ S/ACORN_J ┆           ┆           ┆           ┆   ┆ _control" ┆           ┆           ┆          │
│ CU_…      ┆           ┆           ┆           ┆   ┆ , "…      ┆           ┆           ┆          │
│ s3://imos ┆ -31.60957 ┆ -29.36351 ┆ 153.01056 ┆ … ┆ ["LATITUD ┆ null      ┆ NETCDF3_C ┆ null     │
│ -data/IMO ┆ 8         ┆ 3         ┆ 1         ┆   ┆ E_quality ┆           ┆ LASSIC    ┆          │
│ S/ACORN_J ┆           ┆           ┆           ┆   ┆ _control" ┆           ┆           ┆          │
│ CU_…      ┆           ┆           ┆           ┆   ┆ , "…      ┆           ┆           ┆          │
│ s3://imos ┆ -24.19581 ┆ -21.92031 ┆ 150.78170 ┆ … ┆ ["LATITUD ┆ null      ┆ NETCDF3_C ┆ null     │
│ -data/IMO ┆ 2         ┆           ┆ 1         ┆   ┆ E_quality ┆           ┆ LASSIC    ┆          │
│ S/ACORN_J ┆           ┆           ┆           ┆   ┆ _control" ┆           ┆           ┆          │
│ CU_…      ┆           ┆           ┆           ┆   ┆ , "…      ┆           ┆           ┆          │
│ s3://imos ┆ -37.45496 ┆ -34.82342 ┆ 132.95395 ┆ … ┆ ["LATITUD ┆ null      ┆ NETCDF3_C ┆ null     │
│ -data/IMO ┆ 6         ┆ 5         ┆ 7         ┆   ┆ E_quality ┆           ┆ LASSIC    ┆          │
│ S/ACORN_J ┆           ┆           ┆           ┆   ┆ _control" ┆           ┆           ┆          │
│ CU_…      ┆           ┆           ┆           ┆   ┆ , "…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (14_660, 3)
┌─────────────────────────────────┬──────────────────────┬─────────────────────────────────┐
│ s3_uri                          ┆ collection           ┆ metadata                        │
│ ---                             ┆ ---                  ┆ ---                             │
│ str                             ┆ str                  ┆ str                             │
╞═════════════════════════════════╪══════════════════════╪═════════════════════════════════╡
│ s3://imos-data/IMOS/DWM/SOTS/2… ┆ DWM                  ┆ {"file_format": "NETCDF4", "gl… │
│ s3://imos-data/IMOS/DWM/SOTS/2… ┆ DWM                  ┆ {"file_format": "NETCDF4", "gl… │
│ s3://imos-data/IMOS/DWM/ASFS/S… ┆ DWM                  ┆ {"file_format": "NETCDF3_CLASS… │
│ s3://imos-data/IMOS/DWM/ASFS/S… ┆ DWM                  ┆ {"file_format": "NETCDF3_CLASS… │
│ s3://imos-data/IMOS/DWM/ASFS/S… ┆ DWM                  ┆ {"file_format": "NETCDF3_CLASS… │
│ …                               ┆ …                    ┆ …                               │
│ s3://imos-data/IMOS/ACORN_JCU_… ┆ ACORN_JCU_historical ┆ {"file_format": "NETCDF3_CLASS… │
│ s3://imos-data/IMOS/ACORN_JCU_… ┆ ACORN_JCU_historical ┆ {"file_format": "NETCDF3_CLASS… │
│ s3://imos-data/IMOS/ACORN_JCU_… ┆ ACORN_JCU_historical ┆ {"file_format": "NETCDF3_CLASS… │
│ s3://imos-data/IMOS/ACORN_JCU_… ┆ ACORN_JCU_historical ┆ {"file_format": "NETCDF3_CLASS… │
│ s3://imos-data/IMOS/ACORN_JCU_… ┆ ACORN_JCU_historical ┆ {"file_format": "NETCDF3_CLASS… │
└─────────────────────────────────┴──────────────────────┴─────────────────────────────────┘

In [10]:
# Construct generator
metadata = (orjson.loads(metadata) for metadata in udf["metadata"])

# Build schema
schema_builder = genson.SchemaBuilder()
for metadata in metadata:
    schema_builder.add_object(metadata)

# Extract schema
schema = schema_builder.to_schema()

In [17]:
# Sort global attribute keys naturally (human-like)
sorted_global_attribute_keys = natsort.natsorted(
    seq=[k for k in schema["properties"]["global_attrs"]["properties"]],
    alg=natsort.IGNORECASE,
)
print(sorted_global_attribute_keys)

['absolute_orbit_number', 'abstract', 'acknowledgement', 'acknowledgment', 'acs_data_set', 'acs_file', 'additionalhistory', 'age_class', 'agency_in_charge', 'aims_channel_id', 'author', 'author_email', 'averaging_period', 'Biofouling', 'buoy_specification_url', 'cal_data_description', 'Calibration_Data', 'Callsign', 'cdm_data_type', 'cdm_timeseries_variables', 'circular_redundancy_code', 'citation', 'collecting_period', 'comment', 'comment_archive', 'comment_ctd_post_dip', 'comment_ctd_pre_dip', 'comment_data_qc', 'comment_data_qc_report', 'comment_deck_height', 'comment_fast_sampling_period_ms', 'comment_file_settings_Ch1', 'comment_file_settings_Ch2', 'comment_file_settings_Channel', 'comment_file_settings_Channel_Count', 'comment_file_settings_CoefDate', 'comment_file_settings_Comments', 'comment_file_settings_Cycle_Unit', 'comment_file_settings_Data_Flag', 'comment_file_settings_DepAdjRho', 'comment_file_settings_End_Time', 'comment_file_settings_EndTime', 'comment_file_settings_File_Name', 'comment_file_settings_File_Type', 'comment_file_settings_Immersion_Effect', 'comment_file_settings_ImmersionEN', 'comment_file_settings_Info_File', 'comment_file_settings_Inst_No', 'comment_file_settings_Inst_Type', 'comment_file_settings_Interval', 'comment_file_settings_Old_ImmersionEN', 'comment_file_settings_Raw_File', 'comment_file_settings_Read_Flag', 'comment_file_settings_Sample_Count', 'comment_file_settings_SampleCnt', 'comment_file_settings_SensorType', 'comment_file_settings_SensorType2', 'comment_file_settings_SensorType3', 'comment_file_settings_SondeName', 'comment_file_settings_SondeNo', 'comment_file_settings_Start_Time', 'comment_file_settings_StartTime', 'comment_file_settings_Status', 'comment_file_settings_StopTime', 'comment_file_settings_Time_Unit', 'comment_flux_calculation', 'comment_generating_script', 'comment_height', 'comment_instrument', 'comment_instrument_setup', 'comment_PCO2_data', 'comment_recovery', 'comment_setup_burst_interval', 'comment_setup_burst_program', 'comment_setup_burst_samples', 'comment_setup_caldate', 'comment_setup_darkslope', 'comment_setup_darkyint', 'comment_setup_depthslope', 'comment_setup_depthyint', 'comment_setup_detector', 'comment_setup_detector_output', 'comment_setup_detector_units', 'comment_setup_endtime', 'comment_setup_fwhm', 'comment_setup_gain', 'comment_setup_imm', 'comment_setup_in_air', 'comment_setup_in_water', 'comment_setup_int_scalar', 'comment_setup_lat', 'comment_setup_lon', 'comment_setup_lowbatt_th', 'comment_setup_samplerate', 'comment_setup_sampling_mode', 'comment_setup_sd_logfile', 'comment_setup_starttime', 'comment_setup_sunrise_offset', 'comment_setup_sunset_offset', 'comment_setup_temp_interval', 'comment_setup_tempco', 'comment_setup_timezone', 'comment_setup_utc', 'comment_setup_vlowbatt_th', 'comment_setup_wavelengths', 'comment_setup_wipe_interval', 'comment_slow_sampling_period_ms', 'comment_time', 'comment_uncertainty', 'common_name', 'compliance_checker_imos_version', 'compliance_checker_last_updated', 'compliance_checker_version', 'compliance_checks_passed', 'contact', 'contributor_email', 'contributor_name', 'contributor_role', 'contributor_type', 'contributor_url', 'Conventions', 'conventions', 'coord_system', 'cor_data_description', 'Creator', 'creator_email', 'creator_institution', 'creator_name', 'creator_type', 'creator_url', 'credit', 'cruise_id', 'csiro_indian_ocean_temperature_archive_id', 'cyclic_redundancy_code', 'data_assembly_center', 'Data_Center', 'data_center_email', 'data_centre', 'data_centre_email', 'data_comment', 'data_mode', 'data_product_type', 'data_quality_notes', 'data_source', 'data_take_id_hex', 'data_type', 'Data_Type', 'DATE:', 'date_created', 'date_issued', 'date_metadata_modified', 'date_modified', 'date_update', 'Day_or_Night', 'days_since_deployment', 'deck_unit_serial_number', 'deployment', 'deployment_code', 'deployment_date', 'Deployment_id', 'deployment_id', 'deployment_number', 'Deployment_year', 'depth_below_sea_water_surface', 'depth_correction_applied', 'derived_product_type', 'description_Cosine', 'description_Ed', 'description_Lsky', 'description_Lu', 'description_url', 'device_file', 'device_files_Ed', 'device_files_Lsky', 'device_files_Lu', 'device_id', 'disclaimer', 'distribution_statement', 'distribution_statment', 'DSD_entry_id', 'Earth-Sun_Distance_Correction', 'easternmost_longitude', 'Easternmost_Longitude', 'End_Center_Latitude', 'End_Center_Longitude', 'End_Day', 'End_Millisec', 'End_Node', 'End_Time', 'End_Time_Format', 'End_Year', 'extended_delayed_descriptor_factor', 'facility_code', 'feature_type', 'featureType', 'featuretype', 'file', 'file_quality_index', 'file_quality_level', 'file_version', 'file_version_quality_control', 'filename', 'firmware_date', 'firmware_parameters', 'firmware_version', 'Flag_Percentages', 'format_version', 'gds_version_id', 'GDS_version_id', 'generating_code_version', 'geophysical_calibration_constant_mean', 'geophysical_calibration_constant_median', 'geophysical_calibration_constant_median_percentile', 'geophysical_model_function', 'geospatial_bounds', 'geospatial_bounds_crs', 'geospatial_geo_reference_datum', 'geospatial_lat_max', 'geospatial_lat_min', 'geospatial_lat_resolution', 'geospatial_lat_units', 'geospatial_lon_max', 'geospatial_lon_min', 'geospatial_lon_resolution', 'geospatial_lon_units', 'geospatial_vertical_max', 'geospatial_vertical_min', 'geospatial_vertical_negative', 'geospatial_vertical_positive', 'geospatial_vertical_reference_datum', 'geospatial_vertical_units', 'Graphical_User_Interface_Version', 'gts_insertion_node', 'gtspp_digitisation_method_code', 'gtspp_precision_code', 'Hardware_serial_number', 'Hardware_version', 'history', 'history_of_appended_files', 'hull_serial_number', 'id', 'id_tag', 'imei_log1', 'imei_log2', 'IMO', 'imo_number', 'included_values_flagged_as', 'indicator_for_digitization', 'input_file', 'Input_Files', 'Input_Parameters', 'institution', 'institution_address', 'institution_postal_address', 'institution_references', 'instr_id', 'instrument', 'instrument_ave_version', 'instrument_average_interval', 'instrument_azimuth_angle', 'instrument_beam_angle', 'instrument_burst_duration', 'instrument_burst_interval', 'instrument_burst_unit', 'instrument_burst_units', 'instrument_calibration_date', 'instrument_ctd_model', 'instrument_ctd_serialnumber', 'instrument_firmware_version', 'instrument_fw_version', 'instrument_head_serial_number', 'instrument_header_01', 'instrument_header_02', 'instrument_header_03', 'instrument_header_04', 'instrument_header_05', 'instrument_header_06', 'instrument_header_07', 'instrument_header_08', 'instrument_header_09', 'instrument_header_10', 'instrument_header_11', 'instrument_header_12', 'instrument_header_13', 'instrument_header_14', 'instrument_header_15', 'instrument_header_16', 'instrument_header_17', 'instrument_header_18', 'instrument_header_19', 'instrument_header_20', 'instrument_header_21', 'instrument_header_22', 'instrument_header_23', 'instrument_header_24', 'instrument_header_25', 'instrument_header_26', 'instrument_header_27', 'instrument_header_28', 'instrument_header_29', 'instrument_header_30', 'instrument_header_31', 'instrument_header_32', 'instrument_header_33', 'instrument_header_34', 'instrument_header_35', 'instrument_header_36', 'instrument_header_37', 'instrument_header_38', 'instrument_header_39', 'instrument_header_40', 'instrument_header_41', 'instrument_header_42', 'instrument_header_43', 'instrument_header_44', 'instrument_header_45', 'instrument_header_46', 'instrument_header_47', 'instrument_header_48', 'instrument_header_49', 'instrument_header_50', 'instrument_header_51', 'instrument_header_52', 'instrument_header_53', 'instrument_header_54', 'instrument_header_55', 'instrument_header_56', 'instrument_header_57', 'instrument_header_58', 'instrument_header_59', 'instrument_header_60', 'instrument_header_61', 'instrument_header_62', 'instrument_header_63', 'instrument_header_64', 'instrument_header_65', 'instrument_header_66', 'instrument_header_67', 'instrument_header_68', 'instrument_header_69', 'instrument_header_70', 'instrument_header_71', 'instrument_header_72', 'instrument_header_73', 'instrument_header_74', 'instrument_header_75', 'instrument_header_76', 'instrument_header_77', 'instrument_header_78', 'instrument_header_79', 'instrument_header_80', 'instrument_header_81', 'instrument_header_82', 'instrument_header_83', 'instrument_header_84', 'instrument_header_85', 'instrument_header_86', 'instrument_header_87', 'instrument_header_88', 'instrument_imu', 'instrument_imu_model', 'instrument_imu_serial_number', 'instrument_maker', 'instrument_model', 'instrument_nominal_depth', 'instrument_nominal_height', 'instrument_part_number', 'instrument_sample_interval', 'instrument_sampling_interval', 'instrument_serial_number', 'instrument_serial_number_Ed', 'instrument_serial_number_Lsky', 'instrument_serial_number_Lu', 'internal_source_file', 'is_the_data_public', 'ISAR-QC', 'ISAR-QC_version', 'jcool', 'jcool_comment', 'jwarm', 'jwarm_comment', 'jwave', 'jwave_comment', 'keywords', 'keywords_vocabulary', 'LAC_Pixel_Start_Number', 'LAC_Pixel_Subsampling', 'Latitude', 'latitude', 'Latitude_Units', 'license', 'lineage', 'loc_algorithm', 'local_time_zone', 'location', 'logger', 'logger_serial_number', 'logger_time', 'Longitude', 'longitude', 'Longitude_Units', 'Lower_Left_Latitude', 'Lower_Left_Longitude', 'Lower_Right_Latitude', 'Lower_Right_Longitude', 'manufacture_date', 'Mask_Names', 'measurement_frequency', 'Metadata_Conventions', 'Metadata_Link', 'metadata_uuid', 'method_water_temp_and_or_sal_measurement', 'Mission', 'Mission_Characteristics', 'model', 'Mooring', 'mooring', 'Name:', 'naming_authority', 'nation', 'NCO', 'nco_openmp_thread_number', 'netcdf_version', 'Netcdf_version', 'netCDF_version', 'netcdf_version_id', 'Node_Crossing_Time', 'Node_Crossing_Time_Format', 'nortek_averaging_interval', 'nortek_blank_distance', 'nortek_firmware_version', 'nortek_head_frequency_kHz', 'nortek_mesurement_interval', 'nortek_number_beams', 'nortek_receive_length', 'nortek_time_between_pings', 'nortek_time_bewteen_bursts', 'nortek_tx_pulse_length', 'northernmost_latitude', 'Northernmost_Latitude', 'notes', 'number_chla_profiles', 'number_doxy_profiles', 'number_light_profiles', 'Number_of_Bands', 'Number_of_Pixel_Control_Points', 'number_of_profiles', 'Number_of_Scan_Control_Points', 'Number_of_Scan_Lines', 'number_of_t_profiles', 'number_of_ts_profiles', 'Orbit_Node_Longitude', 'Orbit_Number', 'organization', 'percent_coverage', 'PI', 'pi_name', 'Pixels_per_Scan_Line', 'platform', 'platform_code', 'Platform_code', 'platform_deployment_cruise_ExpoCode', 'platform_deployment_cruise_name', 'platform_deployment_ship_ICES', 'platform_deployment_ship_name', 'platform_launch_date', 'platform_recovery_cruise_ExpoCode', 'platform_recovery_cruise_name', 'platform_recovery_ship_ICES', 'platform_recovery_ship_name', 'platform_vocabulary', 'positive', 'postdrop_comments', 'predrop_comments', 'principal_investigator', 'principal_investigator_email', 'Processing_Control', 'processing_level', 'Processing_Time', 'Processing_Time_Format', 'Processing_Version', 'processing_version', 'Product_Creation', 'Product_Creation_Format', 'product_id_hex', 'Product_Name', 'product_type', 'product_version', 'program', 'project', 'project_acknowledgement', 'ptt', 'publisher_email', 'publisher_institution', 'publisher_name', 'publisher_type', 'publisher_url', 'qc_method', 'quality_control', 'quality_control_indicator', 'quality_control_log', 'quality_control_set', 'quality_control_threshold_fail_log', 'Recorder_firmware_version', 'Recorder_software_version', 'reference', 'reference_datum', 'reference_doi', 'reference_file_name', 'references', 'rejected_files', 'release_site', 'rtc_data_description', 'sampling_rate', 'Scene_Center_Latitude', 'Scene_Center_Longitude', 'Scene_Center_Scan_Line', 'Scene_Center_Solar_Zenith', 'Scene_Center_Time', 'Scene_Center_Time_Format', 'sea_bird_data_conversion_01_datcnv_date', 'sea_bird_data_conversion_02_datcnv_in', 'sea_bird_data_conversion_03_datcnv_skipover', 'sea_bird_data_conversion_04_datcnv_ox_hysteresis_correction', 'sea_bird_data_conversion_05_datcnv_ox_tau_correction', 'sea_bird_firmware_date', 'sea_bird_firmware_version', 'sea_bird_manufacture_date', 'sensor', 'Sensor', 'Sensor_Characteristics', 'Sensor_Name', 'serial_number', 'sex', 'ship_id', 'ship_name', 'ship_transect_number', 'site', 'site_code', 'site_depth_at_deployment', 'site_name', 'site_nominal_depth', 'smru_platform_code', 'software_id', 'Software_Name', 'Software_Version', 'sot_id', 'sot_id_statement', 'source', 'source_data', 'source_file', 'source_file_download', 'source_file_opendap', 'source_netcdf', 'source_ocn_safe', 'source_path', 'sourceFilename', 'southernmost_latitude', 'Southernmost_Latitude', 'spatial_resolution', 'species', 'spectral_analysis_technique', 'spectral_analysis_technique_reference', 'spotter_id', 'ssr_Analysis', 'ssr_Chirp_Direction', 'ssr_Chirp_Duration', 'ssr_Chirp_Duration_units', 'ssr_Chirp_Shape', 'ssr_Data_Type', 'ssr_N_Chirps', 'ssr_Radar', 'ssr_Ranging', 'ssr_RF_Bandwidth', 'ssr_RF_Bandwidth_units', 'ssr_RF_Frequency', 'ssr_RF_Frequency_units', 'ssr_Rx_Boresight', 'ssr_Rx_Boresight_units', 'ssr_Rx_Latitude', 'ssr_Rx_Latitude_units', 'ssr_Rx_Longitude', 'ssr_Rx_Longitude_units', 'ssr_Rx_N_Elements', 'ssr_Stations', 'ssr_Technology', 'ssr_Tx_Latitude', 'ssr_Tx_Latitude_units', 'ssr_Tx_Longitude', 'ssr_Tx_Longitude_units', 'standard_name_voabulary', 'standard_name_vocabulary', 'Start_Center_Latitude', 'Start_Center_Longitude', 'start_date', 'Start_Day', 'Start_Millisec', 'Start_Node', 'start_time', 'Start_Time', 'Start_Time_Format', 'Start_Year', 'state_country', 'Station_Latitude', 'Station_Longitude', 'Station_Name', 'stop_date', 'stop_time', 'subsetVariables', 'summary', 'system1', 'system2', 'tag_type', 'temp_correction_applied', 'thermal_lag_adjustment', 'time_coverage_duration', 'time_coverage_end', 'time_coverage_resolution', 'time_coverage_start', 'time_deployment_end', 'time_deployment_end_origin', 'time_deployment_start', 'time_deployment_start_origin', 'title', 'Title', 'toolbox_input_file', 'toolbox_version', 'transmission', 'transmit_receive_polarisation', 'trip_id', 'tsc_data_description', 'Upper_Left_Latitude', 'Upper_Left_Longitude', 'Upper_Right_Latitude', 'Upper_Right_Longitude', 'uuid', 'VERSION:', 'version_database', 'vessel_name', 'voyage_deployment', 'voyage_deployment_start_date', 'voyage_number', 'voyage_recovery', 'voyage_recovery_bottom', 'voyage_recovery_start_date', 'voyage_recovery_top', 'watch_circle', 'watch_circle_units', 'water_depth', 'water_depth_reference', 'water_depth_units', 'wave_buoy_type', 'wave_motion_sensor_type', 'wave_sensor_serial_number', 'westernmost_longitude', 'Westernmost_Longitude', 'wigos_id', 'WMO', 'wmo_platform_code', 'XBT_calibration_OFFS', 'XBT_calibration_OFFSET', 'XBT_calibration_SCAL', 'XBT_calibration_SCALE', 'XBT_cruise_ID', 'XBT_height_launch_above_water_in_meters', 'XBT_input_filename', 'XBT_instrument_serialnumber', 'XBT_line', 'XBT_line_description', 'XBT_manufacturer_date_yyyymmdd', 'XBT_probetype_fallrate_equation', 'XBT_probetype_fallrate_equation_DEPTH', 'XBT_probetype_fallrate_equation_DEPTH_RAW', 'XBT_recorder_type', 'XBT_uniqueid', 'zi', 'zi_comment']